name: cd

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/menumkr-api
            git fetch
            git reset --hard origin/master
            chown -R www-data:www-data .
            composer install --quiet --optimize-autoloader --apcu-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan migrate:fresh --force --seed
