name: cd

on:
  push:
    tags:
      - '*'

jobs:
  cd:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            chown -R www-data:www-data menumkr-api
            cd menumkr-api
            composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
