name: docker

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Install PHP dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Export user
        run: export WWWUSER=${WWWUSER:-$UID}

      - name: Export group
        run: export WWWGROUP=${WWWGROUP:-$(id -g)}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./vendor/laravel/sail/runtimes/8.2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/menumkr-api:latest, ${{ secrets.DOCKERHUB_USERNAME }}/menumkr-api:${{ steps.vars.outputs.tag }}